version: '2'
services:
  teamspeak:
    image: mbentley/teamspeak
    restart: always
    ports:
      - ${PORT9987}:9987/udp
      - ${PORT10011}:10011
      - ${PORT30033}:30033
    volumes:
      - /data/teamspeak:/data
