version: '2'
catalog:
  name: "Teamspeak"
  version: "v1.0"
  description: "TS3 mit DB"
  uuid: teamspeak-1
  minimum_rancher_version: v1.2.0
  questions:
    - variable: "PORT9987"
      label: "Port 9987 für TS"
      description: "Port 9987"
      required: true
      default: "9987"
      type: "int"

    - variable: "PORT10011"
      label: "Port 10011 für TS"
      description: "Port 10011"
      required: true
      default: "10011"
      type: "int"

    - variable: "PORT30033"
      label: "Port 30033 für TS"
      description: "Port 30033"
      required: true
      default: "30033"
      type: "int"

teamspeak:
