mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: ${PASSWORD_DB}
  ports:
    - 3306:3306
  dns: ${dnsserver}
  dns_search: ${dnssearch}
guacd:
    image: guacamole/guacd
    ports:
      -4822:4822
    dns: ${dnsserver}
    dns_search: ${dnssearch}
guacamole:
  image: guacamole/guacamole
  environment:
    MYSQL_DATABASE: ${db}
    MYSQL_USER: ${db_user}
    MYSQL_PASSWORD: ${PASSWORD_DB}
  links:
    - guacd:guacd
    - mysql:mysql
  ports:
    - 8080:8080
  dns: ${dnsserver}
  dns_search: ${dnssearch}
